name:                smooth
version:             0.1.0.0
github:              "githubuser/smooth"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/smooth#readme>

dependencies:
- mono-traversable
- base >= 4.7 && < 5
- sized
- type-natural
- vector
- lens
- singletons
- ghc-typelits-knownnat
- ghc-typelits-presburger
- equational-reasoning
- halg-core
- ghc-typelits-natnormalise
- singletons-presburger
- halg-polynomials
- algebra
- algebraic-prelude
- containers
- foldl
- halg-algorithms
- profunctors
- semialign
- these
- adjunctions
- linear
- hashable
- unordered-containers
- ListLike
- reflection

library:
  source-dirs: src
  dependencies:
  - factorials

executables:
  smooth-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - smooth
    - simple-reflect
    - algebra
    - transformers
    - lens
    - dlist

tests:
  smooth-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - smooth
    - ad
    - tasty
    - these
    - semialign-indexed
    - type-natural
    - sized >= 0.4.0.0
    - generic-random
    - vector
    - mono-traversable
    - ListLike
    - ghc-typelits-knownnat
    - singletons
    - quickcheck-instances
    - QuickCheck
    - tasty-discover
    - tasty-quickcheck
    - vector
    - halg-core

benchmarks:
  diffupto-bench:
    main: diffupto-bench.hs
    source-dirs: bench
    dependencies:
    - smooth
    - gauge
